import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { chatApi, fileApi } from '../../api/api';
import { autoFillFromAI } from './complaintSlice';

// Async Thunk: Initialize or Create Active Chat Session
export const initChatSessionThunk = createAsyncThunk(
  'chat/initSession',
  async (existingChatId = null, { rejectWithValue }) => {
    try {
      if (existingChatId) {
        const detail = await chatApi.getChat(existingChatId);
        return detail;
      }
      const newChat = await chatApi.createChat({ title: 'AI Copilot Complaint Session' });
      return newChat;
    } catch (err) {
      return rejectWithValue(err.message || 'Failed to initialize chat session');
    }
  }
);

// Async Thunk: Send Message to AI Copilot
export const sendMessageThunk = createAsyncThunk(
  'chat/sendMessage',
  async ({ chatId, content }, { dispatch, rejectWithValue }) => {
    try {
      const response = await chatApi.sendMessage(chatId, content);
      
      // Auto-fill form fields if AI extracted structured data
      if (response.extracted_data) {
        dispatch(autoFillFromAI(response.extracted_data));
      }

      return response;
    } catch (err) {
      return rejectWithValue(err.message || 'Failed to send message to AI Copilot');
    }
  }
);

// Async Thunk: Upload Attachment File & Poll Background Processing Status
export const uploadChatFileThunk = createAsyncThunk(
  'chat/uploadFile',
  async ({ file, chatId }, { dispatch, rejectWithValue }) => {
    try {
      const fileRes = await fileApi.uploadFile(file, chatId);

      // Poll background file status if pending
      if (fileRes?.id && fileRes?.status === 'PENDING') {
        const pollInterval = 1500; // 1.5 seconds
        const maxAttempts = 30; // 45 seconds max
        let attempts = 0;

        while (attempts < maxAttempts) {
          await new Promise((resolve) => setTimeout(resolve, pollInterval));
          attempts += 1;
          try {
            const statusRes = await fileApi.getFile(fileRes.id);
            if (statusRes?.status === 'COMPLETED' || statusRes?.status === 'FAILED') {
              break;
            }
          } catch (pollErr) {
            console.warn('File polling attempt error:', pollErr);
          }
        }
      }

      // Re-fetch chat detail with all new messages generated by background ARQ worker
      let updatedChat = null;
      if (chatId) {
        updatedChat = await chatApi.getChat(chatId);
        if (updatedChat?.messages?.length > 0) {
          const aiMsgs = updatedChat.messages.filter(
            (m) => m.sender === 'ai' && (m.extra_data || m.extracted_data)
          );
          if (aiMsgs.length > 0) {
            const latestAiMsg = aiMsgs[aiMsgs.length - 1];
            const dataToFill = latestAiMsg.extra_data || latestAiMsg.extracted_data;
            if (dataToFill) {
              dispatch(autoFillFromAI(dataToFill));
            }
          }
        }
      }

      return { fileRes, updatedChat };
    } catch (err) {
      return rejectWithValue(err.message || 'Failed to upload attachment file');
    }
  }
);

export const chatSlice = createSlice({
  name: 'chat',
  initialState: {
    activeChatId: null,
    messages: [],
    uploadedFiles: [],
    isLoading: false,
    isUploading: false,
    error: null,
  },
  reducers: {
    clearChatError: (state) => {
      state.error = null;
    },
    resetChatSession: (state) => {
      state.activeChatId = null;
      state.messages = [];
      state.uploadedFiles = [];
      state.error = null;
    },
  },
  extraReducers: (builder) => {
    builder
      // initChatSessionThunk
      .addCase(initChatSessionThunk.pending, (state) => {
        state.isLoading = true;
        state.error = null;
      })
      .addCase(initChatSessionThunk.fulfilled, (state, action) => {
        state.isLoading = false;
        state.activeChatId = action.payload.id;
        state.messages = action.payload.messages || [];
      })
      .addCase(initChatSessionThunk.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload || 'Could not load chat session';
      })

      // sendMessageThunk
      .addCase(sendMessageThunk.pending, (state, action) => {
        state.isLoading = true;
        state.error = null;
        // Optimistically add user message to UI
        state.messages.push({
          id: Date.now(),
          chat_id: action.meta.arg.chatId,
          sender: 'user',
          content: action.meta.arg.content,
          created_at: new Date().toISOString(),
        });
      })
      .addCase(sendMessageThunk.fulfilled, (state, action) => {
        state.isLoading = false;
        // Replace or append AI message
        if (action.payload.ai_message) {
          state.messages.push({
            ...action.payload.ai_message,
            extracted_data: action.payload.extracted_data,
          });
        }
      })
      .addCase(sendMessageThunk.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload || 'Failed to receive AI response';
      })

      // uploadChatFileThunk
      .addCase(uploadChatFileThunk.pending, (state) => {
        state.isUploading = true;
        state.error = null;
      })
      .addCase(uploadChatFileThunk.fulfilled, (state, action) => {
        state.isUploading = false;
        const { fileRes, updatedChat } = action.payload || {};
        if (fileRes) {
          state.uploadedFiles.push(fileRes);
        }
        if (updatedChat?.messages) {
          state.messages = updatedChat.messages;
        }
      })
      .addCase(uploadChatFileThunk.rejected, (state, action) => {
        state.isUploading = false;
        state.error = action.payload || 'Failed to upload file';
      });
  },
});

export const { clearChatError, resetChatSession } = chatSlice.actions;
export default chatSlice.reducer;
